//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeaceHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Billings = new HashSet<Billing>();
        }
    
        public int paymentId { get; set; }
        public int BookingId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<int> paymentTotal { get; set; }
        public string paymentMethod { get; set; }
        public string paymentStatus { get; set; }
        public Nullable<int> deleted { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
