//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeaceHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Bookings = new HashSet<Booking>();
            this.savedRooms = new HashSet<savedRoom>();
        }
    
        public int roomId { get; set; }
        public int roomTypeId { get; set; }
        public byte[] roomImg { get; set; }
        public Nullable<int> roomNumber { get; set; }
        public Nullable<int> roomTotalBooked { get; set; }
        public string roomStatus { get; set; }
        public Nullable<double> roomPrice { get; set; }
        public Nullable<int> deleted { get; set; }
        public byte[] roomImg2 { get; set; }
        public byte[] roomImg3 { get; set; }
        public string roomName { get; set; }
        public string roomDescription { get; set; }
        public string roomProvided { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual RoomType RoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<savedRoom> savedRooms { get; set; }
    }
}
